steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',

        '--build-arg',
        'DATABASE_URL=$STAGING_DATABASE_URL',

        '-t',
        'europe-west10-docker.pkg.dev/licenseplate-checker/licenseplate-checker-staging/licenseplate-checker-staging-image',
        '.',
      ]
    secretEnv: ['STAGING_DATABASE_URL']

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west10-docker.pkg.dev/licenseplate-checker/licenseplate-checker-staging/licenseplate-checker-staging-image',
      ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'licenseplate-checker-staging-service'
      - '--image'
      - 'europe-west10-docker.pkg.dev/licenseplate-checker/licenseplate-checker-staging/licenseplate-checker-staging-image'
      - '--region'
      - 'europe-west10'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Remove if you want restricted access

# Specify logs bucket
logsBucket: gs://licenseplate-checker-logs

# Define secrets
availableSecrets:
  secretManager:
    - versionName: projects/683398294242/secrets/STAGING_DATABASE_URL/versions/latest
      env: STAGING_DATABASE_URL
