services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:vHv8ctJKxZMtQWeJM9VH4WrUa9bD@localhost:5432/mydb?schema=public
      ENVIRONMENT: development
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vHv8ctJKxZMtQWeJM9VH4WrUa9bD
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
